{
 "title": "MM2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MM2 Replication Latency Average (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_mirror_source_connector_replication_latency_ms_avg",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "MM2 Consumer Lag (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{topic!=\"connect-offsets-kafka-connect-fargate\", topic!=\"connect-status-kafka-connect-fargate\", topic!=\"connect-configs-kafka-connect-fargate\", topic!=\"mm2-offset-syncs_mskdest_internal\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "MM2 Source Record Ages (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_mirror_source_connector_record_age_ms_avg",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "MM2 Consumer Fetch Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "MM2 Source Task Record Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_active_count{connector!=\"mm2-hbc\"}",
     "legendFormat": "{{ connector }}-{{task}}"
    },
    {
     "expr": "kafka_consumer_incoming_byte_total{clientId=~\"consumer-mm2-msc-cons-[0-9]+\"}/1000000"
    }
   ]
  }
 ]
}